### ISSUE TITLE
Support bulk-delete

### ISSUE THREAD

**Issue by SuperSajuuk** [Azareal/SajuukBot#1]
Should we include support for using the bulk-delete endpoint? This would allow the bot to clear out channels using a specific command, which would help when you need to clear out important channels to re-purpose them for later use.

**Comment by Azareal** [comment]
Maybe. It's probably easier to just delete the channel and remake it.
I'll think about it.

**Comment by SuperSajuuk** [comment]
@Azareal Low priority is fine for me on this. If needed, it can be a modular extension that users can choose to enable if they need it.

**Comment by SuperSajuuk** [comment]
A !clean command exists in the bot, which will bulk delete posts from a channel (either all users, or a specific targeted user). The Discord API limits requests for this endpoint to the most recent 2 weeks of posts.
