### ISSUE TITLE
DM outputs (if any) should respond with a reaction if possible

### ISSUE THREAD

**Issue by PointyDev** [Azareal/SajuukBot#40]
Something along the lines of this:

![dm reaction](https://google.took-my-blobs-away-from.me/and-im-gonna-mod-android-oreo/97fbdf.png)

@SuperSajuuk

**Comment by SuperSajuuk** [comment]
The bot has no DM related support, in fact we explicitly "return False" when the `message.channel.is_private` attribute is returned. Thus, reacting to indicate that a DM was sent is kinda pointless.
