### ISSUE TITLE
Provide alternate command names for some commands

### ISSUE THREAD

**Issue by SuperSajuuk** [Azareal/SajuukBot#46]
Some commands should be given an alias that can allow for alternat server formatting to be used. Eg `!r add` as an alias for `!remind`, as the former is a common syntax used by those servers using rowboat

**Comment by Tarek1337** [comment]
Going full rowboat? :^)

**Comment by SuperSajuuk** [comment]
Implemented and deployed for reminders ONLY (`!r add` and `!r clear` are valid aliases to `!remind` and `!remind clear`)
